FROM ubuntu

RUN apt update && apt upgrade -y
RUN apt install -y git sudo zsh less
RUN echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >>/etc/sudoers
RUN useradd -m sirenityk
RUN groupadd wheel
RUN usermod -aG wheel sirenityk

USER sirenityk
WORKDIR /home/sirenityk
ARG PYENV=false
ARG UV=false
ARG NVM=false
COPY . dotfiles
RUN bash dotfiles/run.sh
RUN sudo rm -fr dotfiles .bash*
RUN sudo apt autopurge -y
RUN sudo apt clean -y

CMD ["/usr/bin/zsh"]
